### ISSUE TITLE
How can we run tests in 1 thread(maybe more) and use concurrency? 

### ISSUE THREAD

**Issue by mishanya1772** [CrispusDH/puppeteer-ava-selenoid#4]
Hi!
Do you know, how we can run e2e tests using concurrency? 

Because at the moment in your solution, AVA opens as many windows as there are tests and in this situation, I am not sure, that we use concurrency(looks like Parallel running).

Also we can use:
test.**serial**('requires to run serially', t => {
  // ...
});

and tests will run in 1 thread. But I am also not sure, that we use concurrency in this situation.
So, do you have any ideas, how we can run tests in 1 thread and use concurrency?

**Comment by CrispusDH** [comment]
Concurrency will work if you will have more than one file. You could take a look how it works in AVA documentation.
